steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build 
    args: 
      - "build"
      - "-t"
      - "gcr.io/project-funky-flex/stedi-chikaberry:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - "push"
      - "gcr.io/project-funky-flex/stedi-chikaberry:latest"

  #This step deploys teh dev application in kubernettes
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: Deploy
    args: 
    - run
    - --filename=mainfest.yaml
    - --image=gcr.io/project-funky-flex/stedi-chikaberry:latest
    - --location=us-east4-b
    - --output=/tmp/outputdev
    - --cluster=cluster-1


  - name: "gcr.io/cloud-builders/docker"
    id: run
    args:
      - "run"
      - "gcr.io/project-funky-flex/stedi-chikaberry:latest"


