steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build 
    args: 
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stedi-chikaberry:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/stedi-chikaberry:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: run
    args:
      - "run"
      - "gcr.io/$PROJECT_ID/stedi-chikaberry:latest"


