steps:
#this steps build the container image

  - name: "gcr.io/cloud-builders/docker"
    id: build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stedi-tests-chika:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
      id: push
      args:
        - "push"
        - "gcr.io/$PROJECT_ID/stedi-tests-chika:latest"